# Generated by Django 6.0 on 2025-12-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_proctorsession_proctorevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorevent',
            name='code_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
