# Generated by Django 6.0 on 2025-12-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_proctorsession_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorsession',
            name='live_frame',
            field=models.TextField(blank=True, null=True),
        ),
    ]
