-- Create table if not exists to ensure schema is correct
CREATE TABLE IF NOT EXISTS student_interests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_email TEXT NOT NULL,
  interest_category TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE student_interests ENABLE ROW LEVEL SECURITY;

-- Re-create policies safely (Drop if exists first)

-- Select Policy
DROP POLICY IF EXISTS "Students can view own interests" ON student_interests;
CREATE POLICY "Students can view own interests" ON student_interests
FOR SELECT USING (student_email = (auth.jwt() ->> 'email'));

-- Insert Policy
DROP POLICY IF EXISTS "Students can insert own interests" ON student_interests;
CREATE POLICY "Students can insert own interests" ON student_interests
FOR INSERT WITH CHECK (student_email = (auth.jwt() ->> 'email'));

-- Delete Policy
DROP POLICY IF EXISTS "Students can delete own interests" ON student_interests;
CREATE POLICY "Students can delete own interests" ON student_interests
FOR DELETE USING (student_email = (auth.jwt() ->> 'email'));
