# Generated by Django 6.0 on 2025-12-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_proctorevent_code_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctorsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
