# Generated by Django 6.0 on 2025-12-19 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_proctorsession_live_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProctorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('FACE', 'Face Detection'), ('GAZE', 'Gaze Direction'), ('OBJECT', 'Object Detection'), ('BEHAVIOR', 'Behavioral Analysis'), ('COMPREHENSIVE', 'Full Analysis')], default='COMPREHENSIVE', max_length=20)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('anomalies', models.JSONField(default=list)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='execution.proctorevent')),
            ],
            options={
                'verbose_name_plural': 'AI Proctor Analyses',
                'ordering': ['-timestamp'],
            },
        ),
    ]
